from typing import Optional

import typer

from passman.password_manager import (
    copy_password,
    initialize,
    list_passwords,
    remove_password,
    save_password,
)

app = typer.Typer()


@app.command()
def init(
    filepath: Optional[str] = None,
    master_password: Optional[str] = None,
):
    """
    Initialize a password manager passman profile.

    Note:
        The master password should be very secure and be saved in a safe place.

    Args:
        master_password (Optional[str]): The master password used to secure all the other accounts.
        filepath (Optional[str]): The master password used to secure all the other accounts.
    """

    if not master_password:
        typer.echo("\nEnter your Master Password:")
        typer.echo(
            "* Ensure that the password is strong and hidden safely.\n"
            "Leave empty to automatically generate a secure master password."
        )
        master_password = typer.prompt("> ", default="", hide_input=True)

    if not filepath:
        typer.echo("\nEnter configuration filepath:")
        typer.echo(
            "* Where you want your configuration file stored "
            "(Choose a hidden place to keep stalkers away).\n"
            "Default: ~/.passman/<auto-generated-name>"
        )
        filepath = typer.prompt("> ", default="")

    # @TODO: Verify filepath integrity and existance.

    return initialize(master_password, filepath)


@app.command()
def new(
    name: str = typer.Option(..., prompt="Enter Account name (e.g. Github)"),
    password: Optional[str] = typer.Option(
        "",
        prompt="Enter Account password.",
        help="If empty, a strong password will be auto-generated.",
        hide_input=True,
    ),
    username: Optional[str] = typer.Option("", prompt="Enter Account username"),
    url: Optional[str] = typer.Option("", prompt="Enter Account URL"),
    description: Optional[str] = typer.Option("", prompt="Enter Account Description"),
):
    """
    Add new account with to passman.

    Args:
        name (str): Account name.
        password (Optional[str]): The password to encrypt, automatically generated if not provided.
        username (Optional[str]): The account username
        url (Optional[str]): The url / service where the password is used.
        description (Optional[str]): A password description.
    """
    return save_password(name, password, username, url, description)


@app.command()
def accounts():
    """List all available accounts."""

    return list_passwords()


@app.command()
def copy(name: str = typer.Option(..., prompt="Account name or index")):
    """
    Copy the password of the account with the provided ID or index to the clipboard.

    N.B: You can find the index next to an account's name in the accounts list.

    Args:
        name (str): The target password identifier.
    """
    account_id: str | int = name
    try:
        account_id = int(account_id) - 1
    except ValueError:
        pass
    return copy_password(account_id)


@app.command()
def remove(
    name: str = typer.Option(..., prompt="Account name"),
):
    """
    Remove a password.

    Args:
        name (str): The target password identifier.
        master_password (str): The master password.
    """
    confirm = typer.confirm(f"Are you sure you want to delete {name} account?")
    if confirm:
        return remove_password(name)
    else:
        typer.echo("Operation canceled.")


if __name__ == "__main__":
    app()
