# Author:      Mouad KOMMIR < mouadkommir@gmail.com>
# Description: This workflow will upload Onilock to PyPI when a new release is created

name: Publish Onilock to Pypi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gpg xclip
          python -m venv venv
          source venv/bin/activate
          pip install -r all_requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover

      - name: Build release distributions
        run: |
          source venv/bin/activate
          pip install -r all_requirements.txt
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/onilock/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
